pluginManagement {
    repositories {
        gradlePluginPortal()
        mavenCentral()
    }
}

dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        mavenCentral()
    }
}

rootProject.name = 'mini_ecommerce'

include 'common'
include 'plan_service'
include 'inventory_service'
include 'order_service'
include 'payment_service'
include 'shipping_service'
include 'pricing_service'
include 'notification_service'
include 'analytics_service'
include 'user_service'
include 'seed_service'

