server:
  port: 8083

spring:
  application:
    name: order_service
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
  datasource:
    url: jdbc:postgresql://localhost:5432/order_service
    username: ecommerce_user
    password: ecommerce_password
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

app:
  kafka:
    topics:
      order-placed: ${KAFKA_TOPIC_ORDER_PLACED:order.placed}
