server:
  port: 8088

spring:
  application:
    name: payment_service
  datasource:
    url: jdbc:postgresql://localhost:5432/payment_service
    username: ecommerce_user
    password: ecommerce_password
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
