spring:
  application:
    name: seed_service
  main:
    web-application-type: none
  datasource:
    url: jdbc:postgresql://localhost:5432/seed_service
    username: ecommerce_user
    password: ecommerce_password

seed:
  targets:
    - name: plan_service
      url: jdbc:postgresql://localhost:5432/plan_service
      username: ecommerce_user
      password: ecommerce_password
      change-log: classpath:db/changelog/plan/db.changelog-master.xml
