plugins {
    id 'java-library'
}

group = 'com.miniecommerce'
version = '0.0.1-SNAPSHOT'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

dependencies {
    api platform('org.springframework.boot:spring-boot-dependencies:3.3.5')
    api 'org.springframework:spring-web'
    api 'com.fasterxml.jackson.core:jackson-databind'
    api 'io.github.openfeign:feign-core:13.14'

    testImplementation 'org.junit.jupiter:junit-jupiter:5.10.5'
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}

tasks.withType(Test).configureEach {
    useJUnitPlatform()
}
